/**
 * Built-in closed-world diagram modules.
 *
 * This file exposes the built-in registry and re-exports concrete diagram
 * module definitions from per-diagram folders under `src/diagrams/`.
 * @module main/builtin
 */

import { DiagramModuleRegistry } from "./registry.mjs";
import { BUILTIN_DIAGRAM_MODULES } from "../diagrams/index.mjs";

export {
  BUILTIN_DIAGRAM_MODULES,
  ActivityDiagramAssets,
  ActivityDiagramDocs,
  ActivityDiagramLayout,
  ActivityDiagramModule,
  ActivityDiagramParser,
  ActivityDiagramRenderer,
  ActivityDiagramSecurity,
  ActivityDiagramTests,
  activityDiagramModule,
  ClassDiagramAssets,
  ClassDiagramDocs,
  ClassDiagramLayout,
  ClassDiagramModule,
  ClassDiagramParser,
  ClassDiagramRenderer,
  ClassDiagramSecurity,
  ClassDiagramTests,
  classDiagramModule,
  ComponentDiagramAssets,
  ComponentDiagramDocs,
  ComponentDiagramLayout,
  ComponentDiagramModule,
  ComponentDiagramParser,
  ComponentDiagramRenderer,
  ComponentDiagramSecurity,
  ComponentDiagramTests,
  componentDiagramModule,
  DEFAULT_ACTIVITY_PLUGINS,
  DEFAULT_CLASS_PLUGINS,
  DEFAULT_COMPONENT_PLUGINS,
  DEFAULT_DEPLOYMENT_PLUGINS,
  DEFAULT_OBJECT_PLUGINS,
  DEFAULT_SEQUENCE_PLUGINS,
  DEFAULT_STATE_PLUGINS,
  DEFAULT_USE_CASE_PLUGINS,
  DeploymentDiagramAssets,
  DeploymentDiagramDocs,
  DeploymentDiagramLayout,
  DeploymentDiagramModule,
  DeploymentDiagramParser,
  DeploymentDiagramRenderer,
  DeploymentDiagramSecurity,
  DeploymentDiagramTests,
  deploymentDiagramModule,
  ObjectDiagramAssets,
  ObjectDiagramDocs,
  ObjectDiagramLayout,
  ObjectDiagramModule,
  ObjectDiagramParser,
  ObjectDiagramRenderer,
  ObjectDiagramSecurity,
  ObjectDiagramTests,
  objectDiagramModule,
  StateDiagramAssets,
  StateDiagramDocs,
  StateDiagramLayout,
  StateDiagramModule,
  StateDiagramParser,
  StateDiagramRenderer,
  StateDiagramSecurity,
  StateDiagramTests,
  stateDiagramModule,
  SequenceDiagramAssets,
  SequenceDiagramDocs,
  SequenceDiagramLayout,
  SequenceDiagramModule,
  SequenceDiagramParser,
  SequenceDiagramRenderer,
  SequenceDiagramSecurity,
  SequenceDiagramTests,
  sequenceDiagramModule,
  UseCaseDiagramAssets,
  UseCaseDiagramDocs,
  UseCaseDiagramLayout,
  UseCaseDiagramModule,
  UseCaseDiagramParser,
  UseCaseDiagramRenderer,
  UseCaseDiagramSecurity,
  UseCaseDiagramTests,
  useCaseDiagramModule,
} from "../diagrams/index.mjs";

/** @public */
export const defaultDiagramModuleRegistry = new DiagramModuleRegistry({
  modules: [...BUILTIN_DIAGRAM_MODULES],
  frozen: true,
});
